# Generated by Django 4.2.11 on 2026-05-27 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('normalization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('flagged', 'Flagged'), ('rejected', 'Rejected'), ('edited', 'Edited'), ('comment', 'Comment')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('field_changed', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_actions', to='normalization.normalizedrecord')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
    ]
