# Generated by Django 4.2.11 on 2026-05-27 06:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('1', 'Scope 1 (Direct)'), ('2', 'Scope 2 (Electricity)'), ('3', 'Scope 3 (Value Chain)')], max_length=1)),
                ('source_type', models.CharField(max_length=20)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('activity_date', models.DateField(null=True)),
                ('quantity', models.FloatField(null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('co2e_kg', models.FloatField(null=True)),
                ('facility', models.CharField(blank=True, max_length=255)),
                ('cost_center', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('extra_data', models.JSONField(default=dict)),
                ('review_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('flagged', 'Flagged'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('suspicion_reasons', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_manually_edited', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='ingestion.ingestionbatch')),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized', to='ingestion.rawrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-activity_date', 'source_type'],
                'indexes': [models.Index(fields=['tenant', 'scope'], name='normalizati_tenant__c73b22_idx'), models.Index(fields=['tenant', 'review_status'], name='normalizati_tenant__faaa60_idx'), models.Index(fields=['batch'], name='normalizati_batch_i_ca1ef9_idx')],
            },
        ),
    ]
